### ISSUE TITLE
NextJS example does not work with NextJS13

### ISSUE THREAD

**Issue by phoenixy1** [plaid/tiny-quickstart#21]
Reported by a user:

the nextjs quikstart is not compatible with the newest version of next 13
specifically, the getServerSideProps in the dash page dont work with next js 13

@leerob I don't suppose you might be able to help with this? We will obviously try and fix it if you don't have the bandwidth, but we don't have domain expertise with NextJS here so you might be better positioned to address it. Thanks!

**Comment by ToddKerpelman** [comment]
Hmm... I got it working okay with these dependencies.
```
    "iron-session": "^6.1.3",
    "next": "^13.4.19",
    "plaid": "^15.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-plaid-link": "^3.4.0"
```

Did the user give any more details on the error they were seeing?

**Comment by phoenixy1** [comment]
@ToddKerpelman no. That said, looking at the version history there was a nextjs release just 2 days before this bug was reported (v13.4.15) that contains a bug fix for behavior related to getServerSideProps, so maybe that release fixed it?  Anyway, I wouldn't worry about it if it works now. I never tried to repro this
