### ISSUE TITLE
`run-p` command not found when running `npm start` in the `react` directory

### ISSUE THREAD

**Issue by ValentaTomas** [plaid/tiny-quickstart#7]
Because the package https://www.npmjs.com/package/npm-run-all is missing from the dev dependencies the command `run-p` that's supposed to be executed is not found.

**Comment by phoenixy1** [comment]
@ValentaTomas Hmm...I checked and it looks like npm-run-all *is* in the dev dependencies in the react directory?

**Comment by ValentaTomas** [comment]
I'm sorry, this was my mistake - I automatically run `npm install` in the *top* folder and then looked to `vanilla_js/package.json` for `npm-run-all` by mistake.
